services:
# ========================= [ MONGODB ] ========================= #
  mongodb:
    image: mongo:7
    container_name: db_MongoDB
    restart: always
    ports:
      - "${MONGO_PORT:-27017}:${MONGO_INTERNAL_PORT:-27017}"
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    networks:
      - db_network
# ======================== [ PostgreSQL ] ======================= #
  postgresql:
    image: postgres:16
    container_name: db_PostgreSQL
    restart: always
    ports:
      - "${POSTGRESQL_PORT:-5432}:${POSTGRESQL_INTERNAL_PORT:-5432}"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    networks:
      - db_network
# ======================== [ SQL SERVER ] ======================= #
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: db_MSSQLServer
    restart: always
    ports:
      - "${MSSQL_PORT:-1433}:${MSSQL_INTERNAL_PORT:-1433}"
    user: root
    environment:
      ACCEPT_EULA: ${ACCEPT_EULA}
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
      MSSQL_PID: ${MSSQL_PID}
    volumes:
      - mssql_data:/var/opt/mssql
    networks:
      - db_network
# ========================= [ MySQL ] ========================== #
  mysql:
    image: mysql:8.0
    container_name: db_MySQL
    restart: always
    ports:
      - "${MYSQL_PORT:-3306}:${MYSQL_INTERNAL_PORT:-3306}"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - db_network
# ========================= [ Redis ] ========================== #
  redis:
    image: redis:7-alpine
    container_name: db_Redis
    restart: always
    ports:
      - "${REDIS_PORT:-6379}:${REDIS_INTERNAL_PORT:-6379}"
    command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - db_network

# ======================== [ GLOBALES ] ======================== #
volumes:
  mongodb_data:
  postgresql_data:
  mssql_data:
  mysql_data:
  redis_data:

networks:
  db_network:
    driver: bridge
